version: "3.5"

networks:
  demo:
    external: true

services:
  zk1:
    image: hyperledger/fabric-zookeeper:x86_64-0.4.6
    hostname: zk1
    #ports:
    #  - '2181'
    #  - '2888'
    #  - '3888'
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888 server.4=zk4:2888:3888
    networks:
      demo:
        aliases:
          - zk1
    deploy:
      placement:
        constraints:
          - node.hostname == k1

  zk2:
    image: hyperledger/fabric-zookeeper:x86_64-0.4.6
    hostname: zk2
    environment:
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888 server.4=zk4:2888:3888
    networks:
      demo:
        aliases:
          - zk2
    deploy:
      placement:
        constraints:
          - node.hostname == k2

  zk3:
    image: hyperledger/fabric-zookeeper:x86_64-0.4.6
    hostname: zk3
    environment:
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888 server.4=zk4:2888:3888
    networks:
      demo:
        aliases:
          - zk3
    deploy:
      placement:
        constraints:
          - node.hostname == k3
  zk4:
    image: hyperledger/fabric-zookeeper:x86_64-0.4.6
    hostname: zk4
    environment:
      - ZOO_MY_ID=4
      - ZOO_SERVERS=server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888 server.4=zk4:2888:3888
    networks:
      demo:
        aliases:
          - zk4
    deploy:
      placement:
        constraints:
          - node.hostname == k4

  kafka1:
    image: hyperledger/fabric-kafka:x86_64-0.4.6
    hostname: kafka1
    environment:
      - KAFKA_MESSAGE_MAX_BYTES=103809024 # 99 * 1024 * 1024 B
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024 # 99 * 1024 * 1024 B
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      # KAFKA SPECIFIC
      - KAFKA_BROKER_ID=1
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zk1:2181,zk2:2181,zk3:2181,zk4:2181
    networks:
      demo:
        aliases:
          - kafka1
    deploy:
      placement:
        constraints:
          - node.hostname == k1

  kafka2:
    image: hyperledger/fabric-kafka:x86_64-0.4.6
    hostname: kafka2
    environment:
      - KAFKA_MESSAGE_MAX_BYTES=103809024 # 99 * 1024 * 1024 B
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024 # 99 * 1024 * 1024 B
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      # KAFKA SPECIFIC
      - KAFKA_BROKER_ID=2
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zk1:2181,zk2:2181,zk3:2181,zk4:2181
    networks:
      demo:
        aliases:
          - kafka2
    deploy:
      placement:
        constraints:
          - node.hostname == k2

  kafka3:
    image: hyperledger/fabric-kafka:x86_64-0.4.6
    hostname: kafka3
    environment:
      - KAFKA_MESSAGE_MAX_BYTES=103809024 # 99 * 1024 * 1024 B
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024 # 99 * 1024 * 1024 B
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      # KAFKA SPECIFIC
      - KAFKA_BROKER_ID=3
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zk1:2181,zk2:2181,zk3:2181,zk4:2181
    networks:
      demo:
        aliases:
          - kafka3
    deploy:
      placement:
        constraints:
          - node.hostname == k3

  kafka4:
    image: hyperledger/fabric-kafka:x86_64-0.4.6
    hostname: kafka4
    environment:
      - KAFKA_MESSAGE_MAX_BYTES=103809024 # 99 * 1024 * 1024 B
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024 # 99 * 1024 * 1024 B
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      # KAFKA SPECIFIC
      - KAFKA_BROKER_ID=4
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zk1:2181,zk2:2181,zk3:2181,zk4:2181
    networks:
      demo:
        aliases:
          - kafka4
    deploy:
      placement:
        constraints:
          - node.hostname == k4
