version: '3'

services:
    agent:
        image: portainer/agent:latest
        environment:
            # REQUIRED: Should be equal to the service name prefixed by "tasks." when
            # deployed inside an overlay network
            AGENT_CLUSTER_ADDR: tasks.agent
            # AGENT_PORT: 9001
            # LOG_LEVEL: debug
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - portainer_net
        deploy:
            mode: global
    
    portainer:
        image: portainer/portainer:latest
        command: -H tcp://tasks.agent:9001 --tlsskipverify --admin-password '$$2y$$05$$6v0mMJ5PJ6q4djlSHBjUE.kbUE6PpzvsZTyZXnMaCffhq.aFzcsoK' # P@ssw0rd
        #command: --admin-password '$$2y$$05$$6v0mMJ5PJ6q4djlSHBjUE.kbUE6PpzvsZTyZXnMaCffhq.aFzcsoK'
        ports:
            - "9000:9000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
        networks:
            - portainer_net
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints: [node.role == manager]

networks:
    portainer_net:
        driver: overlay

volumes:
    portainer_data:
