" ###### CREATOR          Ted       
" ###### DESCRIPTION      Vim configuration for Linux, OSX and Windows
" ###### VERSION          v1.2
" ###### UPDATE           2018/5/24


" ===================
" Vundle Installation
" ===================
" Install Vundle on Linux
" -----------------------
" # git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
"
" Install Vundle on Windows
" -------------------------
" cd %USERPROFILE%
" git clone https://github.com/VundleVim/Vundle.vim.git %USERPROFILE%\.vim\bundle\Vundle.vim
"
" Install Vundle plugin
" ---------------------
" Open vim
" :PluginInstall
"

" START Vundle plugins
" --------------------
" For Linux
set rtp+=~/.vim/bundle/Vundle.vim
" For Windows
"set rtp+=%USERPROFILE%/.vim/bundle/Vundle.vim/
"set rtp+=%USERPROFILE%/.vim/bundle/Vundle.vim/
"call vundle#begin('%USERPROFILE%/.vim/bundle/')
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'altercation/vim-colors-solarized.git'
Plugin 'Lokaltog/vim-powerline.git'
Plugin 'scrooloose/nerdtree'
Plugin 'jistr/vim-nerdtree-tabs'
Plugin 'Townk/vim-autoclose'
Plugin 'easymotion/vim-easymotion'
"Plugin 'godlygeek/tabular'
"Plugin 'plasticboy/vim-markdown'
"Plugin 'vim-scripts/taglist.vim'
"Plugin 'Valloric/YouCompleteMe'
Plugin 'davidhalter/jedi-vim'
call vundle#end()
" END Vundle plugins
" ------------------
"
" List of character encodings considered
" when starting to edit an existing file
set fileencodings=utf-8,gb2312,gbk,gb18030,cp936  
" Set the character encoding for the file of this buffer
set fileencoding=utf-8
" Set the character encoding used inside Vim
set encoding=utf-8  
" Encoding used for the terminal
set termencoding=utf-8  


let NERDTreeShowBookmarks=1
" Enable status line for vim-powerline.git
set laststatus=2
let g:Powerline_symbols = 'unicode'


" Enable syntax hightlight
syntax enable
" Number of colors
set t_Co=256
" Show line number
set number
" Show command in the last line
set showcmd
set noswapfile
"set listchars=eol:¬,tab:>·,trail:~,extends:>,precedes:<,space:␣
"set listchars=eol:¬
"set list

" Search pattern ignore case(case insensitive)
set ignorecase
set smartcase
set hlsearch

"let &titlestring = @%
"set title


" This switches 'filetype on'
filetype plugin on 
"filetype on
"filetype plugin indent on


" Number of spaces that a Tab counts for
set tabstop=4
" Number of spaces to use for (auto)indent
set shiftwidth=4
" Use appropriate number of spaces to insert a Tab in Insert Mode
set expandtab
set autoindent
set foldmethod=indent

" ============
" Map settings
" ============
" Insert current time and date after current cursor
map now a<C-R>=strftime("%c")<CR><Esc>
" Use Ctrl+Y to copy select text in Vim
map <C-Y> "+y
" Use Ctrl+P to paste
map <C-P> "*p
" Use Ctrl+# to comment out selected line
map <C-X> <C-V>I# <Esc>

" Open 'Save as' window
map <C-S> :bro sav<CR>

" Double click to hight word
"nnoremap <silent> <2-LeftMouse> :let @/='\<<C-R>=expand("<cword>")<CR>\>'<CR>:set hls<CR>:%s///gn<CR>
nnoremap <silent> <2-LeftMouse> :let @/='\V\<'.escape(expand('<cword>'), '\').'\>'<cr>:set hls<cr>:let @+=expand('<cword>')<cr>

" Press Space to turn off highlighting and clear any message already displayed.
nnoremap <silent> <Space> :nohlsearch<Bar>:echo<CR>
" nnoremap * *<C-O>:%s///gn<CR>

map <F4> :NERDTreeTabsToggle<cr>

" ==========================================================
" The settings below is used for GUI vim,such as GVIM,MacVim
" ==========================================================
if has("gui_running")
    source $VIMRUNTIME/delmenu.vim
    source $VIMRUNTIME/menu.vim
    set langmenu=en
	set guioptions=maAce
    "Linux
	"set guifont=Monospace\ 11
    "Windows, Mac
	"set guifont=Monospace:h11
    "
    set guifont=DejaVu\ Sans\ Mono\ 11
	set showtabline=2
    set guitablabel=%t

    set background=dark
    colorscheme solarized

    "set mousemodel=extend
    highlight Cursor guibg=Green
endif
