version: '3'

volumes:
  esdata:
    driver: local


services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    hostname: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./custom_elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    volumes:
      - ./custom_kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601

