version: '3'

volumes:
  esdata:
    driver: local

networks:
  net:

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    hostname: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./custom_elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      #- /pan/elk/custom_elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    networks:
      net:
        aliases:
          - elasticsearch
    deploy:
      placement:
        constraints:
          - node.hostname = SRV-ELK

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.3
    volumes:
      - ./custom_kibana.yml:/usr/share/kibana/config/kibana.yml
      #- /pan/elk/custom_kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      net:
        aliases:
          - kibana
    deploy:
      placement:
        constraints:
          - node.hostname = SRV-ELK

