version: '3.5'

networks:
    net:
        driver: overlay 
        attachable: true

volumes:
    data0:
    data1:
    data2:
    config0:
    config1:
    config2:

services:
    haproxy:
        # haproxy-ldap image need to be build using Dockerfile
        # under the same folder:
        # docker build -t haproxy-ldap:v2 .
        
        #image: haproxy-ldap:v2

        # OR
        image: haproxy
        volumes:
            - "/pan/openldap-ha/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
        #
        #
        hostname: haproxy
        ports:
            - "389:389"
        networks:
            net:
        deploy:
            placement:
                constraints:
                    #- node.role == manager
                    - node.hostname == SRV-HTTP

    openldap0:
        image: osixia/openldap
        hostname: openldap0
        environment:
            LDAP_ORGANISATION: xinlian
            LDAP_DOMAIN: cetcxl.com
            LDAP_BASE_DN: dc=cetcxl,dc=com
            LDAP_CONFIG_PASSWORD: P@ssw0rd
            LDAP_ADMIN_PASSWORD: P@ssw0rd
            LDAP_REPLICATION: "true"
            LDAP_REPLICATION_HOST: "['ldap://openldap0','ldap://openldap1','ldap://openldap2']"
            #LDAP_REPLICATION_HOST: #PYTHON2BASH:['ldap://openldap0','ldap://openldap1','ldap://openldap2']
            #LDAP_REPLICATION_CONFIG_SYNCPROV: binddn='cn=admin,cn=config' bindmethod=simple credentials=P@ssw0rd searchbase='cn=config' type=refreshAndPersist retry='60 +' timeout=3 starttls=critical
            #LDAP_REPLICATION_DB_SYNCPROV: binddn='cn=admin,dc=cetcxl,dc=com' bindmethod=simple credentials=P@ssw0rd searchbase='dc=cetcxl,dc=com' type=refreshAndPersist interval=00:00:00:10 retry='60 +' timeout=3 starttls=critical

        volumes:
            - data0:/var/lib/ldap
            - config0:/etc/ldap/slapd.d
        #ports:
        #    - "389:389"
        networks:
            net:
                aliases:
                    - openldap0
        deploy:
            placement:
                constraints:
                    - node.hostname == SRV-Bak

    openldap1:
        image: osixia/openldap
        hostname: openldap1
        environment:
            LDAP_ORGANISATION: xinlian
            LDAP_DOMAIN: cetcxl.com
            LDAP_BASE_DN: dc=cetcxl,dc=com
            LDAP_CONFIG_PASSWORD: P@ssw0rd
            LDAP_ADMIN_PASSWORD: P@ssw0rd
            LDAP_REPLICATION: "true"
            LDAP_REPLICATION_HOST: "['ldap://openldap0','ldap://openldap1','ldap://openldap2']"
            #LDAP_REPLICATION_HOST: #PYTHON2BASH:['ldap://openldap0','ldap://openldap1','ldap://openldap2']
            #LDAP_REPLICATION_CONFIG_SYNCPROV: binddn='cn=admin,cn=config' bindmethod=simple credentials=P@ssw0rd searchbase='cn=config' type=refreshAndPersist retry='60 +' timeout=3 starttls=critical
            #LDAP_REPLICATION_DB_SYNCPROV: binddn='cn=admin,dc=cetcxl,dc=com' bindmethod=simple credentials=P@ssw0rd searchbase='dc=cetcxl,dc=com' type=refreshAndPersist interval=00:00:00:10 retry='60 +' timeout=3 starttls=critical
        volumes:
            - data1:/var/lib/ldap
            - config1:/etc/ldap/slapd.d
        #ports:
        #    - "1389:389"
        networks:
            net:
                aliases:
                    - openldap1
        deploy:
            placement:
                constraints:
                    - node.hostname == SRV-Bak

    openldap2:
        image: osixia/openldap
        hostname: openldap2
        environment:
            LDAP_ORGANISATION: xinlian
            LDAP_DOMAIN: cetcxl.com
            LDAP_BASE_DN: dc=cetcxl,dc=com
            LDAP_CONFIG_PASSWORD: P@ssw0rd
            LDAP_ADMIN_PASSWORD: P@ssw0rd
            LDAP_REPLICATION: "true"
            LDAP_REPLICATION_HOST: "['ldap://openldap0','ldap://openldap1','ldap://openldap2']"
            #LDAP_REPLICATION_HOST: #PYTHON2BASH:['ldap://openldap0','ldap://openldap1','ldap://openldap2']
            #LDAP_REPLICATION_CONFIG_SYNCPROV: binddn='cn=admin,cn=config' bindmethod=simple credentials=P@ssw0rd searchbase='cn=config' type=refreshAndPersist retry='60 +' timeout=3 starttls=critical
            #LDAP_REPLICATION_DB_SYNCPROV: binddn='cn=admin,dc=cetcxl,dc=com' bindmethod=simple credentials=P@ssw0rd searchbase='dc=cetcxl,dc=com' type=refreshAndPersist interval=00:00:00:10 retry='60 +' timeout=3 starttls=critical
        volumes:
            - data2:/var/lib/ldap
            - config2:/etc/ldap/slapd.d
        #ports:
        #    - "2389:389"
        networks:
            net:
                aliases:
                    - openldap2
        deploy:
            placement:
                constraints:
                    - node.hostname == SRV-ELK
