version: "3"

networks:
  banana-net:
    external: true
  apple-net:
    external: true
  orange-net:
    external: true

services:
  web:
    image: httptarget
    environment:
      NAME: banana
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "8002:80"
    networks:
      - banana-net
      - apple-net
      - orange-net
