version: "3"

networks:
  mynet:
    external: true

services:
  web:
    image: ski2per/hellopy
    environment:
      WHO: World
      REDIS_HOST: redis
    ports:
      - "8001:80"
    networks:
      - mynet

  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    networks:
      - mynet
