version: '3'

services:
  cadvisor:
    image: google/cadvisor
    # hostname is used for distinguishing docker host in Influxdb
    hostname: ted-vm
    # -storage_driver_db=DATABASE_NAME: Database name in Influxdb(default: cadvisor)
    # -storage_driver_host=IP:PORT: IP and Port of Influxdb 
    command: -logtostderr -docker_only -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=172.16.66.6:8086
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
