version: '3'

services:
  logstash:
    image: docker.elastic.co/logstash/logstash:6.5.1
    hostname: logstash
    ports:
      - "5044:5044"
    volumes:
      - ./custom_logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./custom_logstash.conf:/usr/share/logstash/pipeline/logstash.conf
