filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/applog/*.log

processors:
- add_docker_metadata:
    hosts: "unix:///var/run/docker.sock"
#- decode_json_fields:
#    fields: ["log"]

filebeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml
  # Set to true to enable config reloading
  reload.enabled: false

#================ Logstash settings ================
output.logstash:
  hosts: ["172.16.10.10:5044"]
