version: '3.5'

volumes:
  filebeat_data:
  log_vol:

services:
  filebeat:
    build:
      context: ./
      dockerfile: Dockerfile
    #image: filebeat:latest
    image: docker.elastic.co/beats/filebeat:6.5.1
    hostname: SRV-HTTP
    volumes:
      - "./custom_filebeat.yml:/usr/share/filebeat/filebeat.yml"
      - "filebeat_data:/usr/share/filebeat/data:rw"
      - "log_vol:/usr/share/filebeat/applog/:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    user: root

  nginx:
  image: nginx:latest
  container_name: nginx-app
  volumes:
    - "log_vol:/var/log/nginx"



